version: "2"
services:

  ustorage:
    container_name: rails-storage
    image: minio/minio
    command: server /export
    env_file:
      - "env/common.env"
      - "env/storage.env"
    ports:
      - "9000:9000"
    volumes:
      - "./vols/storage:/export"
      - "./conf/minio:/root/.minio"

  uredis:
    container_name: rails-cache
    image: redis
    env_file:
      - "env/common.env"
      - "env/cache.env"
    ports:
      - "16379:6379"
    links:
      - "ustorage:storage"
    volumes:
      - "./vols/cache:/var/lib/rails_redis"

  udatabase:
    container_name: rails-db
    image: mysql
    env_file:
      - "env/common.env"
      - "env/database.env"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    ports:
      - "13306:3306"
    links:
      - "ustorage:storage"
    volumes:
      - "./vols/data:/var/lib/rails_db"

  urevproxy:
    container_name: rails-rev
    image: nginx
    env_file:
      - "env/common.env"
      - "env/rproxy.env"
    ports:
      - "80:80"
    links:
      - "uhost"
    volumes:
      - "./conf/nginx:/etc/nginx/conf.d"

  uapp:
    build: build/uapp
    env_file:
      - "env/common.env"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    tty: True

  uhost:
    extends:
      service: uapp
    container_name: uhost
    ports:
      - "3000:3000"
    links:
      - "udatabase:db"
      - "uredis:cache"
      - "ustorage:storage"
    volumes:
      - "./vols/app:/var/app"

  uworker:
    extends:
      service: uapp
    container_name: uworker
    ports:
      - "3001:3000"
    links:
      - "udatabase:db"
      - "uredis:cache"
      - "ustorage:storage"
    volumes:
      - "./vols/app:/var/worker"
