version: "2"
services:

  udatabase:
    container_name: rails-mysql
    image: mysql
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    tty: True
    volumes:
      - "./rails_db:/rails_db"

#  rredis:
#   images: redis
#
#  volumes:
#    - "./rails_redis:/rails_redis"


#  rproxy:
#    image: nginx
#    ulimits:
#      noproc: 65535
#    volumes:
#      - "./nginx.conf:/etc/nginx/nginx.conf"

  uhost:
    container_name: uhost
    build: uhost_build
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    tty: True
    links:
      - udatabase:db
      - rredis:cache
    volumes:
      - "./rails_app:/rails_app"
