# frozen_string_literal: true
source "https://rubygems.org"

ENV['NOKOGIRI_USE_SYSTEM_LIBRARIES'] = 'YES'

gem "rails", "5.0.0.1"
gem 'sqlite3','1.3.12'
gem 'uglifier','3.0.4'
gem 'sass-rails','5.0.6'
gem 'therubyracer','0.12.2'
gem 'jquery-rails'
gem 'jbuilder','2.6.1'
gem 'turbolinks','5.0.1'
gem 'sdoc'
gem 'bcrypt'
gem 'unicorn','5.2.0'

group :development, :test do
  gem 'byebug','9.0.6'
  gem 'web-console','3.3.0'
  gem 'spring',"2.0.0"
end
